import type { Product } from '@/types'

export interface ExtendedProduct extends Product {
  originalPrice: number
  brand: string
  isNew: boolean
  discount: number
  delivery: string
  specifications: Record<string, string>
  features: string[]
}

export interface DealItem {
  product: ExtendedProduct
  endsIn: string
  label: string
}

export const categories = [
  {
    id: 'cat-1',
    name: 'Electronics',
    slug: 'electronics',
    description: 'Gadgets and devices',
    image: 'https://picsum.photos/seed/electronics/400/400',
    display_order: 1,
    product_count: 8,
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: 'cat-2',
    name: 'Fashion',
    slug: 'fashion',
    description: 'Clothing and accessories',
    image: 'https://picsum.photos/seed/fashion/400/400',
    display_order: 2,
    product_count: 7,
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: 'cat-3',
    name: 'Mobiles',
    slug: 'mobiles',
    description: 'Smartphones and accessories',
    image: 'https://picsum.photos/seed/mobiles/400/400',
    display_order: 3,
    product_count: 5,
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: 'cat-4',
    name: 'Laptops',
    slug: 'laptops',
    description: 'Notebooks and computers',
    image: 'https://picsum.photos/seed/laptops/400/400',
    display_order: 4,
    product_count: 5,
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: 'cat-5',
    name: 'Shoes',
    slug: 'shoes',
    description: 'Footwear for everyone',
    image: 'https://picsum.photos/seed/shoes/400/400',
    display_order: 5,
    product_count: 4,
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: 'cat-6',
    name: 'Watches',
    slug: 'watches',
    description: 'Timepieces and smartwatches',
    image: 'https://picsum.photos/seed/watches/400/400',
    display_order: 6,
    product_count: 3,
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: 'cat-7',
    name: 'Home Appliances',
    slug: 'home-appliances',
    description: 'Appliances for your home',
    image: 'https://picsum.photos/seed/home-appliances/400/400',
    display_order: 7,
    product_count: 4,
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: 'cat-8',
    name: 'Beauty',
    slug: 'beauty',
    description: 'Beauty and personal care',
    image: 'https://picsum.photos/seed/beauty/400/400',
    display_order: 8,
    product_count: 3,
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: 'cat-9',
    name: 'Books',
    slug: 'books',
    description: 'Books and media',
    image: 'https://picsum.photos/seed/books/400/400',
    display_order: 9,
    product_count: 3,
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: 'cat-10',
    name: 'Sports',
    slug: 'sports',
    description: 'Sports and fitness',
    image: 'https://picsum.photos/seed/sports/400/400',
    display_order: 10,
    product_count: 3,
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: 'cat-11',
    name: 'Furniture',
    slug: 'furniture',
    description: 'Home furniture',
    image: 'https://picsum.photos/seed/furniture/400/400',
    display_order: 11,
    product_count: 2,
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: 'cat-12',
    name: 'Accessories',
    slug: 'accessories',
    description: 'Everyday accessories',
    image: 'https://picsum.photos/seed/accessories/400/400',
    display_order: 12,
    product_count: 3,
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: 'cat-13',
    name: 'Groceries',
    slug: 'groceries',
    description: 'Food and essentials',
    image: 'https://picsum.photos/seed/groceries/400/400',
    display_order: 13,
    product_count: 2,
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: 'cat-14',
    name: 'Healthcare',
    slug: 'healthcare',
    description: 'Health and wellness',
    image: 'https://picsum.photos/seed/healthcare/400/400',
    display_order: 14,
    product_count: 2,
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: 'cat-15',
    name: 'Toys',
    slug: 'toys',
    description: 'Toys and games',
    image: 'https://picsum.photos/seed/toys/400/400',
    display_order: 15,
    product_count: 2,
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
]

const baseProducts: ExtendedProduct[] = [
  {
    id: 'prod-1',
    name: 'Sony WH-1000XM5 Wireless Headphones',
    slug: 'sony-wh1000xm5',
    description:
      'Industry-leading noise cancellation with premium sound quality. 30-hour battery life with quick charging. Comfortable lightweight design for all-day wear.',
    price: 348,
    originalPrice: 399,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/headphones1/400/400',
      'https://picsum.photos/seed/headphones2/400/400',
      'https://picsum.photos/seed/headphones3/400/400',
    ],
    category_id: 'cat-1',
    category_name: 'Electronics',
    category_slug: 'electronics',
    tags: ['wireless', 'noise-cancelling', 'bluetooth', 'premium-audio'],
    stock: 45,
    rating: 4.7,
    review_count: 2843,
    brand: 'Sony',
    isNew: false,
    discount: 13,
    delivery: 'Free Delivery',
    specifications: {
      Battery: '30 hours',
      Driver: '30mm',
      Weight: '250g',
      Bluetooth: '5.2',
    },
    features: [
      'Industry-leading noise cancellation',
      '30-hour battery life',
      'Quick charging (3 min = 3 hours)',
      'Multipoint connection',
    ],
    createdAt: '2025-03-15',
  },
  {
    id: 'prod-2',
    name: 'Apple MacBook Pro 16" M3 Max',
    slug: 'macbook-pro-m3',
    description:
      'Supercharged by M3 Max chip with up to 128GB unified memory. Stunning 16-inch Liquid Retina XDR display. Up to 22 hours of battery life.',
    price: 3499,
    originalPrice: 3999,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/macbook1/400/400',
      'https://picsum.photos/seed/macbook2/400/400',
      'https://picsum.photos/seed/macbook3/400/400',
      'https://picsum.photos/seed/macbook4/400/400',
    ],
    category_id: 'cat-4',
    category_name: 'Laptops',
    category_slug: 'laptops',
    tags: ['apple', 'laptop', 'm3', 'professional'],
    stock: 12,
    rating: 4.8,
    review_count: 1523,
    brand: 'Apple',
    isNew: true,
    discount: 12,
    delivery: 'Free Delivery',
    specifications: {
      Chip: 'M3 Max',
      RAM: 'Up to 128GB',
      Display: '16.2" Liquid Retina XDR',
      Battery: '22 hours',
    },
    features: [
      'M3 Max chip',
      '16-inch Liquid Retina XDR display',
      'Up to 22 hours battery',
      'Magic Keyboard with Touch ID',
    ],
    createdAt: '2025-06-01',
  },
  {
    id: 'prod-3',
    name: 'Nike Air Max 270 React',
    slug: 'nike-air-max-270',
    description:
      'Comfort meets style with Nike Air Max 270 React. Featuring a large Air unit and React foam for all-day comfort. Modern silhouette with breathable mesh upper.',
    price: 150,
    originalPrice: 190,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/nike1/400/400',
      'https://picsum.photos/seed/nike2/400/400',
      'https://picsum.photos/seed/nike3/400/400',
    ],
    category_id: 'cat-5',
    category_name: 'Shoes',
    category_slug: 'shoes',
    tags: ['nike', 'sneakers', 'air-max', 'comfort'],
    stock: 78,
    rating: 4.5,
    review_count: 3891,
    brand: 'Nike',
    isNew: false,
    discount: 21,
    delivery: 'Free Delivery',
    specifications: {
      Upper: 'Mesh',
      Sole: 'Rubber',
      Closure: 'Lace-up',
      Weight: '340g',
    },
    features: [
      'Large Air unit for cushioning',
      'React foam midsole',
      'Breathable mesh upper',
      'Durable rubber outsole',
    ],
    createdAt: '2025-02-10',
  },
  {
    id: 'prod-4',
    name: 'Samsung Galaxy S24 Ultra',
    slug: 'samsung-galaxy-s24-ultra',
    description:
      'The ultimate Galaxy experience with Galaxy AI. 200MP camera with 100x Space Zoom. Built-in S Pen. Titanium frame for durability.',
    price: 1299,
    originalPrice: 1399,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/s24ultra1/400/400',
      'https://picsum.photos/seed/s24ultra2/400/400',
      'https://picsum.photos/seed/s24ultra3/400/400',
    ],
    category_id: 'cat-3',
    category_name: 'Mobiles',
    category_slug: 'mobiles',
    tags: ['samsung', 'smartphone', 'android', 'ai'],
    stock: 33,
    rating: 4.6,
    review_count: 2104,
    brand: 'Samsung',
    isNew: false,
    discount: 7,
    delivery: 'Free Delivery',
    specifications: {
      Display: '6.8" Dynamic AMOLED 2X',
      Camera: '200MP',
      RAM: '12GB',
      Storage: '256GB',
    },
    features: [
      'Galaxy AI features',
      '200MP camera with 100x zoom',
      'Built-in S Pen',
      'Titanium frame',
    ],
    createdAt: '2025-01-17',
  },
  {
    id: 'prod-5',
    name: 'LG 65" OLED C3 4K Smart TV',
    slug: 'lg-oled65-c3',
    description:
      'Experience perfect blacks and infinite contrast with LG OLED evo. α9 Gen6 AI processor. Dolby Vision and Dolby Atmos support.',
    price: 1499,
    originalPrice: 1799,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/lgtv1/400/400',
      'https://picsum.photos/seed/lgtv2/400/400',
      'https://picsum.photos/seed/lgtv3/400/400',
    ],
    category_id: 'cat-7',
    category_name: 'Home Appliances',
    category_slug: 'home-appliances',
    tags: ['lg', 'oled', '4k', 'smart-tv'],
    stock: 18,
    rating: 4.7,
    review_count: 987,
    brand: 'LG',
    isNew: false,
    discount: 17,
    delivery: 'Free Delivery',
    specifications: {
      'Screen Size': '65"',
      Resolution: '4K UHD (3840x2160)',
      'Refresh Rate': '120Hz',
      HDMI: '4x HDMI 2.1',
    },
    features: [
      'OLED evo technology',
      'α9 Gen6 AI processor',
      'Dolby Vision + Dolby Atmos',
      '4x HDMI 2.1 ports',
    ],
    createdAt: '2025-04-20',
  },
  {
    id: 'prod-6',
    name: 'Dyson V15 Detect Cordless Vacuum',
    slug: 'dyson-v15-detect',
    description:
      'Intelligent cordless vacuum with laser reveals microscopic dust. Piezo sensor counts particles. Up to 60 minutes of fade-free suction.',
    price: 749,
    originalPrice: 799,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/dyson1/400/400',
      'https://picsum.photos/seed/dyson2/400/400',
      'https://picsum.photos/seed/dyson3/400/400',
    ],
    category_id: 'cat-7',
    category_name: 'Home Appliances',
    category_slug: 'home-appliances',
    tags: ['dyson', 'vacuum', 'cordless', 'smart'],
    stock: 25,
    rating: 4.6,
    review_count: 1456,
    brand: 'Dyson',
    isNew: true,
    discount: 6,
    delivery: 'Free Delivery',
    specifications: {
      'Run Time': '60 min',
      Capacity: '0.76L',
      Weight: '6.8 lbs',
      Filter: 'Washable',
    },
    features: [
      'Laser reveals microscopic dust',
      'Piezo sensor counts particles',
      'Up to 60min run time',
      'Converts to handheld',
    ],
    createdAt: '2025-05-10',
  },
  {
    id: 'prod-7',
    name: 'Bose QuietComfort Ultra Earbuds',
    slug: 'bose-qc-ultra-earbuds',
    description:
      'World-class noise cancellation in a compact design. Immersive spatial audio. Customizable sound with adjustable EQ.',
    price: 299,
    originalPrice: 329,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/bose1/400/400',
      'https://picsum.photos/seed/bose2/400/400',
      'https://picsum.photos/seed/bose3/400/400',
    ],
    category_id: 'cat-1',
    category_name: 'Electronics',
    category_slug: 'electronics',
    tags: ['bose', 'earbuds', 'noise-cancelling', 'spatial-audio'],
    stock: 52,
    rating: 4.5,
    review_count: 1234,
    brand: 'Bose',
    isNew: true,
    discount: 9,
    delivery: 'Free Delivery',
    specifications: {
      Battery: '6 hours (24 with case)',
      Weight: '6.2g per earbud',
      Bluetooth: '5.3',
      'Water Resistance': 'IPX4',
    },
    features: [
      'World-class noise cancellation',
      'Immersive spatial audio',
      'CustomTune technology',
      'IPX4 water resistant',
    ],
    createdAt: '2025-06-15',
  },
  {
    id: 'prod-8',
    name: 'Dell XPS 15 OLED Laptop',
    slug: 'dell-xps-15',
    description:
      'Stunning 15.6-inch 3.5K OLED InfinityEdge display. Intel Core i9-13900H with NVIDIA GeForce RTX 4070. Premium CNC machined aluminum chassis.',
    price: 2499,
    originalPrice: 2799,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/dellxps1/400/400',
      'https://picsum.photos/seed/dellxps2/400/400',
      'https://picsum.photos/seed/dellxps3/400/400',
    ],
    category_id: 'cat-4',
    category_name: 'Laptops',
    category_slug: 'laptops',
    tags: ['dell', 'laptop', 'oled', 'premium'],
    stock: 15,
    rating: 4.4,
    review_count: 876,
    brand: 'Dell',
    isNew: false,
    discount: 11,
    delivery: 'Free Delivery',
    specifications: {
      Processor: 'Intel Core i9-13900H',
      GPU: 'NVIDIA RTX 4070',
      Display: '15.6" 3.5K OLED',
      RAM: '32GB DDR5',
    },
    features: [
      '3.5K OLED InfinityEdge display',
      'Intel Core i9 processor',
      'NVIDIA RTX 4070',
      'CNC aluminum chassis',
    ],
    createdAt: '2025-03-01',
  },
  {
    id: 'prod-9',
    name: 'Adidas Ultraboost Light',
    slug: 'adidas-ultraboost-light',
    description:
      'The lightest Ultraboost ever. New Light BOOST midsole with 10% more energy return. Primeknit+ upper for adaptive fit.',
    price: 190,
    originalPrice: 220,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/adidas1/400/400',
      'https://picsum.photos/seed/adidas2/400/400',
      'https://picsum.photos/seed/adidas3/400/400',
    ],
    category_id: 'cat-5',
    category_name: 'Shoes',
    category_slug: 'shoes',
    tags: ['adidas', 'running', 'boost', 'lightweight'],
    stock: 62,
    rating: 4.6,
    review_count: 2145,
    brand: 'Adidas',
    isNew: false,
    discount: 14,
    delivery: 'Free Delivery',
    specifications: {
      Midsole: 'Light BOOST',
      Upper: 'Primeknit+',
      Weight: '310g',
      Drop: '10mm',
    },
    features: [
      'Lightest Ultraboost ever',
      'Light BOOST with 10% more energy',
      'Primeknit+ adaptive fit',
      'Continental rubber outsole',
    ],
    createdAt: '2025-02-20',
  },
  {
    id: 'prod-10',
    name: 'Apple iPhone 15 Pro Max',
    slug: 'iphone-15-pro-max',
    description:
      'Titanium design with A17 Pro chip. 48MP Main camera with 5x optical zoom. USB-C with USB 3 speeds. Action button for quick access.',
    price: 1199,
    originalPrice: 1299,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/iphone15pm1/400/400',
      'https://picsum.photos/seed/iphone15pm2/400/400',
      'https://picsum.photos/seed/iphone15pm3/400/400',
    ],
    category_id: 'cat-3',
    category_name: 'Mobiles',
    category_slug: 'mobiles',
    tags: ['apple', 'iphone', 'smartphone', 'titanium'],
    stock: 28,
    rating: 4.7,
    review_count: 3456,
    brand: 'Apple',
    isNew: false,
    discount: 8,
    delivery: 'Free Delivery',
    specifications: {
      Chip: 'A17 Pro',
      Display: '6.7" Super Retina XDR',
      Camera: '48MP Main',
      Storage: '256GB',
    },
    features: [
      'Titanium design',
      'A17 Pro chip',
      '48MP camera with 5x zoom',
      'USB-C with USB 3',
    ],
    createdAt: '2025-01-01',
  },
  {
    id: 'prod-11',
    name: 'Apple Watch Series 9',
    slug: 'apple-watch-s9',
    description:
      'Advanced health features with S9 chip. Blood oxygen and ECG sensor. Double tap gesture. Brighter always-on display.',
    price: 399,
    originalPrice: 429,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/awatch1/400/400',
      'https://picsum.photos/seed/awatch2/400/400',
      'https://picsum.photos/seed/awatch3/400/400',
    ],
    category_id: 'cat-6',
    category_name: 'Watches',
    category_slug: 'watches',
    tags: ['apple', 'smartwatch', 'fitness', 'health'],
    stock: 41,
    rating: 4.5,
    review_count: 1876,
    brand: 'Apple',
    isNew: false,
    discount: 7,
    delivery: 'Free Delivery',
    specifications: {
      Chip: 'S9 SiP',
      Display: 'Always-On Retina LTPO OLED',
      Sensors: 'Blood Oxygen, ECG',
      'Water Resistance': 'WR50',
    },
    features: [
      'S9 chip with faster on-device AI',
      'Double tap gesture',
      'Blood oxygen + ECG sensor',
      'Brighter always-on display',
    ],
    createdAt: '2025-01-15',
  },
  {
    id: 'prod-12',
    name: 'Samsung Galaxy Tab S9 Ultra',
    slug: 'samsung-tab-s9-ultra',
    description:
      'Massive 14.6-inch Dynamic AMOLED 2X display. IP68 water and dust resistance. Built-in S Pen with low latency. PC-like multitasking with DeX.',
    price: 1099,
    originalPrice: 1199,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/galaxytab1/400/400',
      'https://picsum.photos/seed/galaxytab2/400/400',
      'https://picsum.photos/seed/galaxytab3/400/400',
    ],
    category_id: 'cat-4',
    category_name: 'Laptops',
    category_slug: 'laptops',
    tags: ['samsung', 'tablet', 'amoled', 's-pen'],
    stock: 20,
    rating: 4.4,
    review_count: 654,
    brand: 'Samsung',
    isNew: false,
    discount: 8,
    delivery: 'Free Delivery',
    specifications: {
      Display: '14.6" Dynamic AMOLED 2X',
      Processor: 'Snapdragon 8 Gen 2',
      RAM: '12GB',
      'Water Resistance': 'IP68',
    },
    features: [
      '14.6-inch Dynamic AMOLED 2X display',
      'IP68 water and dust resistant',
      'Built-in S Pen',
      'Samsung DeX multitasking',
    ],
    createdAt: '2025-02-10',
  },
  {
    id: 'prod-13',
    name: 'JBL Flip 6 Bluetooth Speaker',
    slug: 'jbl-flip-6',
    description:
      'Portable Bluetooth speaker with bold JBL Original Pro Sound. IP67 waterproof and dustproof. 12 hours of playtime. PartyBoost for multi-speaker linking.',
    price: 129,
    originalPrice: 149,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/jbl1/400/400',
      'https://picsum.photos/seed/jbl2/400/400',
      'https://picsum.photos/seed/jbl3/400/400',
    ],
    category_id: 'cat-1',
    category_name: 'Electronics',
    category_slug: 'electronics',
    tags: ['jbl', 'speaker', 'bluetooth', 'portable'],
    stock: 95,
    rating: 4.6,
    review_count: 4567,
    brand: 'JBL',
    isNew: false,
    discount: 13,
    delivery: 'Free Delivery',
    specifications: {
      Power: '30W',
      Battery: '12 hours',
      Waterproof: 'IP67',
      Weight: '550g',
    },
    features: [
      'Bold JBL Original Pro Sound',
      'IP67 waterproof and dustproof',
      '12 hours of playtime',
      'PartyBoost for multi-speaker',
    ],
    createdAt: '2025-04-01',
  },
  {
    id: 'prod-14',
    name: "Levi's 501 Original Fit Jeans",
    slug: 'levis-501-original',
    description:
      'The original blue jean since 1873. Straight leg, button fly. 100% cotton denim. Classic five-pocket design.',
    price: 69,
    originalPrice: 79,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/levis1/400/400',
      'https://picsum.photos/seed/levis2/400/400',
      'https://picsum.photos/seed/levis3/400/400',
    ],
    category_id: 'cat-2',
    category_name: 'Fashion',
    category_slug: 'fashion',
    tags: ['levis', 'jeans', 'denim', 'classic'],
    stock: 120,
    rating: 4.3,
    review_count: 5678,
    brand: "Levi's",
    isNew: false,
    discount: 13,
    delivery: 'Free Delivery',
    specifications: {
      Fit: 'Original Straight',
      Material: '100% Cotton Denim',
      Closure: 'Button Fly',
      Rise: 'Mid Rise',
    },
    features: [
      'Original blue jean since 1873',
      'Straight leg, button fly',
      '100% cotton denim',
      'Classic five-pocket design',
    ],
    createdAt: '2025-01-05',
  },
  {
    id: 'prod-15',
    name: 'Ray-Ban Aviator Classic Sunglasses',
    slug: 'rayban-aviator',
    description:
      'Timeless aviator design with teardrop-shaped lenses. Premium metal frame with adjustable nose pads. UV protection and scratch-resistant lenses.',
    price: 163,
    originalPrice: 203,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/rayban1/400/400',
      'https://picsum.photos/seed/rayban2/400/400',
      'https://picsum.photos/seed/rayban3/400/400',
    ],
    category_id: 'cat-12',
    category_name: 'Accessories',
    category_slug: 'accessories',
    tags: ['rayban', 'sunglasses', 'aviator', 'classic'],
    stock: 55,
    rating: 4.4,
    review_count: 2345,
    brand: 'Ray-Ban',
    isNew: false,
    discount: 20,
    delivery: 'Free Delivery',
    specifications: {
      Frame: 'Metal',
      Lens: 'Scratch-resistant',
      Protection: '100% UV',
      Weight: '30g',
    },
    features: [
      'Timeless aviator design',
      'Premium metal frame',
      'UV protection',
      'Adjustable nose pads',
    ],
    createdAt: '2025-03-10',
  },
  {
    id: 'prod-16',
    name: 'KitchenAid Artisan Stand Mixer',
    slug: 'kitchenaid-artisan',
    description:
      'Legendary KitchenAid Artisan Series 5-Quart stand mixer. 10 speeds with tilt-head design. Durable all-metal construction. 15+ optional attachments.',
    price: 449,
    originalPrice: 499,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/kitchenaid1/400/400',
      'https://picsum.photos/seed/kitchenaid2/400/400',
      'https://picsum.photos/seed/kitchenaid3/400/400',
    ],
    category_id: 'cat-7',
    category_name: 'Home Appliances',
    category_slug: 'home-appliances',
    tags: ['kitchenaid', 'mixer', 'kitchen', 'baking'],
    stock: 22,
    rating: 4.8,
    review_count: 3456,
    brand: 'KitchenAid',
    isNew: false,
    discount: 10,
    delivery: 'Free Delivery',
    specifications: {
      Capacity: '5 Quart',
      Speeds: '10',
      Construction: 'All Metal',
      Motor: 'Powerful DC',
    },
    features: [
      'Legendary Artisan Series',
      '10 speeds with tilt-head',
      'All-metal construction',
      '15+ optional attachments',
    ],
    createdAt: '2025-02-15',
  },
  {
    id: 'prod-17',
    name: 'Rolex Submariner Date',
    slug: 'rolex-submariner',
    description:
      'Iconic diving watch with 300m water resistance. Cerachrom bezel insert. Automatic movement with date function. Oystersteel construction.',
    price: 9500,
    originalPrice: 10000,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/rolex1/400/400',
      'https://picsum.photos/seed/rolex2/400/400',
      'https://picsum.photos/seed/rolex3/400/400',
    ],
    category_id: 'cat-6',
    category_name: 'Watches',
    category_slug: 'watches',
    tags: ['rolex', 'luxury', 'diving', 'automatic'],
    stock: 3,
    rating: 4.9,
    review_count: 456,
    brand: 'Rolex',
    isNew: false,
    discount: 5,
    delivery: 'Free Delivery',
    specifications: {
      Case: '41mm Oystersteel',
      Movement: 'Automatic Calibre 3235',
      'Water Resistance': '300m',
      Bezel: 'Cerachrom',
    },
    features: [
      'Iconic diving watch',
      '300m water resistance',
      'Cerachrom bezel insert',
      'Automatic movement',
    ],
    createdAt: '2025-05-20',
  },
  {
    id: 'prod-18',
    name: 'Amazon Echo Dot 5th Gen',
    slug: 'echo-dot-5',
    description:
      'Smart speaker with Alexa and enhanced audio. Temperature sensor. Built-in motion detection. Night clock feature.',
    price: 49,
    originalPrice: 79,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/echodot1/400/400',
      'https://picsum.photos/seed/echodot2/400/400',
      'https://picsum.photos/seed/echodot3/400/400',
    ],
    category_id: 'cat-1',
    category_name: 'Electronics',
    category_slug: 'electronics',
    tags: ['amazon', 'alexa', 'smart-speaker', 'voice-assistant'],
    stock: 200,
    rating: 4.4,
    review_count: 7890,
    brand: 'Amazon',
    isNew: false,
    discount: 38,
    delivery: 'Free Delivery',
    specifications: {
      Speaker: '1.73" full-range',
      Connectivity: 'Wi-Fi, Bluetooth 5.0',
      Sensors: 'Temperature, Motion',
      Dimensions: '3.9 x 3.9 x 3.5"',
    },
    features: [
      'Alexa voice control',
      'Enhanced audio quality',
      'Temperature sensor',
      'Night clock feature',
    ],
    createdAt: '2025-01-20',
  },
  {
    id: 'prod-19',
    name: 'Herman Miller Aeron Chair',
    slug: 'herman-miller-aeron',
    description:
      'The most iconic office chair ever designed. PostureFit SL back support. 8Z Pellicle suspension for even weight distribution. Fully adjustable arms.',
    price: 1395,
    originalPrice: 1595,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/aeron1/400/400',
      'https://picsum.photos/seed/aeron2/400/400',
      'https://picsum.photos/seed/aeron3/400/400',
    ],
    category_id: 'cat-11',
    category_name: 'Furniture',
    category_slug: 'furniture',
    tags: ['herman-miller', 'office-chair', 'ergonomic', 'premium'],
    stock: 8,
    rating: 4.7,
    review_count: 2341,
    brand: 'Herman Miller',
    isNew: false,
    discount: 13,
    delivery: 'Free Delivery',
    specifications: {
      Material: '8Z Pellicle',
      'Back Support': 'PostureFit SL',
      'Weight Capacity': '350 lbs',
      Warranty: '12 years',
    },
    features: [
      'Iconic ergonomic design',
      'PostureFit SL back support',
      '8Z Pellicle suspension',
      'Fully adjustable',
    ],
    createdAt: '2025-04-10',
  },
  {
    id: 'prod-20',
    name: 'Puma RS-X3 Sneakers',
    slug: 'puma-rsx3',
    description:
      'Bold retro-inspired sneakers with Running System technology. Layered mesh and leather upper. Thick foam midsole for maximum comfort.',
    price: 110,
    originalPrice: 130,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/puma1/400/400',
      'https://picsum.photos/seed/puma2/400/400',
      'https://picsum.photos/seed/puma3/400/400',
    ],
    category_id: 'cat-5',
    category_name: 'Shoes',
    category_slug: 'shoes',
    tags: ['puma', 'sneakers', 'retro', 'fashion'],
    stock: 88,
    rating: 4.3,
    review_count: 1234,
    brand: 'Puma',
    isNew: false,
    discount: 15,
    delivery: 'Free Delivery',
    specifications: {
      Upper: 'Mesh + Leather',
      Sole: 'Rubber',
      Closure: 'Lace-up',
      Technology: 'Running System',
    },
    features: [
      'Retro-inspired design',
      'Running System technology',
      'Layered upper',
      'Thick foam midsole',
    ],
    createdAt: '2025-03-25',
  },
  {
    id: 'prod-21',
    name: 'HP Spectre x360 14',
    slug: 'hp-spectre-x360',
    description:
      'Convertible laptop with 3K2K OLED display. Intel Core Ultra 7. AI-powered features with Intel Arc graphics. Gem-cut design with precision-crafted details.',
    price: 1449,
    originalPrice: 1599,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/hpspectre1/400/400',
      'https://picsum.photos/seed/hpspectre2/400/400',
      'https://picsum.photos/seed/hpspectre3/400/400',
    ],
    category_id: 'cat-4',
    category_name: 'Laptops',
    category_slug: 'laptops',
    tags: ['hp', 'convertible', 'oled', 'ultrabook'],
    stock: 14,
    rating: 4.5,
    review_count: 567,
    brand: 'HP',
    isNew: true,
    discount: 9,
    delivery: 'Free Delivery',
    specifications: {
      Processor: 'Intel Core Ultra 7',
      Display: '14" 3K2K OLED',
      GPU: 'Intel Arc Graphics',
      RAM: '16GB LPDDR5x',
    },
    features: [
      '3K2K OLED touch display',
      'Intel Core Ultra with AI',
      'Gem-cut precision design',
      '360° convertible hinge',
    ],
    createdAt: '2025-06-01',
  },
  {
    id: 'prod-22',
    name: 'Samsung 980 PRO 2TB SSD',
    slug: 'samsung-980-pro',
    description:
      'PCIe 4.0 NVMe SSD with blazing 7,000 MB/s read speeds. Ideal for gaming and creative workloads. Hardware-based AES 256-bit encryption.',
    price: 249,
    originalPrice: 289,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/samsungssd1/400/400',
      'https://picsum.photos/seed/samsungssd2/400/400',
      'https://picsum.photos/seed/samsungssd3/400/400',
    ],
    category_id: 'cat-1',
    category_name: 'Electronics',
    category_slug: 'electronics',
    tags: ['samsung', 'ssd', 'storage', 'nvme'],
    stock: 60,
    rating: 4.7,
    review_count: 2345,
    brand: 'Samsung',
    isNew: false,
    discount: 14,
    delivery: 'Free Delivery',
    specifications: {
      Capacity: '2TB',
      Interface: 'PCIe 4.0 NVMe',
      'Read Speed': '7,000 MB/s',
      'Write Speed': '5,100 MB/s',
    },
    features: [
      'PCIe 4.0 blazing speed',
      '7,000 MB/s read speeds',
      'Hardware-based encryption',
      'Ideal for gaming',
    ],
    createdAt: '2025-02-01',
  },
  {
    id: 'prod-23',
    name: 'Nike Dri-FIT Sportswear Tech Fleece',
    slug: 'nike-tech-fleece',
    description:
      'Premium hoodie with Dri-FIT technology. Tech Fleece fabric for lightweight warmth. Modern athletic fit with zippered pockets.',
    price: 110,
    originalPrice: 130,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/nikefleece1/400/400',
      'https://picsum.photos/seed/nikefleece2/400/400',
      'https://picsum.photos/seed/nikefleece3/400/400',
    ],
    category_id: 'cat-2',
    category_name: 'Fashion',
    category_slug: 'fashion',
    tags: ['nike', 'fleece', 'activewear', 'hoodie'],
    stock: 72,
    rating: 4.4,
    review_count: 1890,
    brand: 'Nike',
    isNew: false,
    discount: 15,
    delivery: 'Free Delivery',
    specifications: {
      Material: 'Dri-FIT Tech Fleece',
      Fit: 'Athletic',
      Pockets: 'Zippered',
      Care: 'Machine Washable',
    },
    features: [
      'Dri-FIT moisture management',
      'Tech Fleece lightweight warmth',
      'Modern athletic fit',
      'Zippered pockets',
    ],
    createdAt: '2025-03-05',
  },
  {
    id: 'prod-24',
    name: 'Google Pixel 8 Pro',
    slug: 'google-pixel-8-pro',
    description:
      'Google AI-powered smartphone with Tensor G3 chip. 50MP main camera with Magic Eraser and Best Take. Super Actua display with smooth 120Hz.',
    price: 899,
    originalPrice: 999,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/pixel8p1/400/400',
      'https://picsum.photos/seed/pixel8p2/400/400',
      'https://picsum.photos/seed/pixel8p3/400/400',
    ],
    category_id: 'cat-3',
    category_name: 'Mobiles',
    category_slug: 'mobiles',
    tags: ['google', 'pixel', 'android', 'ai-camera'],
    stock: 30,
    rating: 4.5,
    review_count: 1456,
    brand: 'Google',
    isNew: false,
    discount: 10,
    delivery: 'Free Delivery',
    specifications: {
      Chip: 'Google Tensor G3',
      Display: '6.7" 120Hz LTPO OLED',
      Camera: '50MP Main',
      Storage: '128GB',
    },
    features: [
      'Tensor G3 AI capabilities',
      'Magic Eraser + Best Take',
      'Super Actua 120Hz display',
      '7 years of updates',
    ],
    createdAt: '2025-01-05',
  },
  {
    id: 'prod-25',
    name: 'Sony PlayStation 5 Console',
    slug: 'playstation-5',
    description:
      'Experience lightning-fast loading with ultra-high-speed SSD. Haptic feedback and adaptive triggers. 4K Blu-ray drive. Tempest 3D AudioTech.',
    price: 499,
    originalPrice: 499,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/ps5_1/400/400',
      'https://picsum.photos/seed/ps5_2/400/400',
      'https://picsum.photos/seed/ps5_3/400/400',
    ],
    category_id: 'cat-1',
    category_name: 'Electronics',
    category_slug: 'electronics',
    tags: ['sony', 'gaming', 'console', 'playstation'],
    stock: 10,
    rating: 4.8,
    review_count: 5678,
    brand: 'Sony',
    isNew: false,
    discount: 0,
    delivery: 'Free Delivery',
    specifications: {
      Storage: '825GB SSD',
      GPU: 'AMD RDNA 2',
      RAM: '16GB GDDR6',
      'Video Output': '4K 120Hz',
    },
    features: [
      'Ultra-high-speed SSD',
      'Haptic feedback controller',
      'Tempest 3D AudioTech',
      '4K Blu-ray',
    ],
    createdAt: '2025-01-10',
  },
  {
    id: 'prod-26',
    name: 'Samsung Galaxy Watch 6 Classic',
    slug: 'galaxy-watch-6-classic',
    description:
      'Premium smartwatch with rotating bezel. BioActive sensor for health tracking. Sleep coaching with sleep stages. Wear OS with Google apps.',
    price: 399,
    originalPrice: 449,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/gwatch6_1/400/400',
      'https://picsum.photos/seed/gwatch6_2/400/400',
      'https://picsum.photos/seed/gwatch6_3/400/400',
    ],
    category_id: 'cat-6',
    category_name: 'Watches',
    category_slug: 'watches',
    tags: ['samsung', 'smartwatch', 'fitness', 'wearos'],
    stock: 35,
    rating: 4.3,
    review_count: 1232,
    brand: 'Samsung',
    isNew: false,
    discount: 11,
    delivery: 'Free Delivery',
    specifications: {
      Display: '1.47" Super AMOLED',
      Processor: 'Exynos W930',
      Sensors: 'BioActive, Temperature',
      Battery: '425mAh',
    },
    features: [
      'Rotating bezel navigation',
      'BioActive health sensor',
      'Sleep coaching',
      'Wear OS with Google apps',
    ],
    createdAt: '2025-04-15',
  },
  {
    id: 'prod-27',
    name: 'Bose SoundLink Max Speaker',
    slug: 'bose-soundlink-max',
    description:
      'Portable Bluetooth speaker with room-filling sound. IP67 waterproof. Up to 20 hours battery. Built-in microphone for calls.',
    price: 399,
    originalPrice: 449,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/bosespeaker1/400/400',
      'https://picsum.photos/seed/bosespeaker2/400/400',
      'https://picsum.photos/seed/bosespeaker3/400/400',
    ],
    category_id: 'cat-1',
    category_name: 'Electronics',
    category_slug: 'electronics',
    tags: ['bose', 'speaker', 'bluetooth', 'waterproof'],
    stock: 28,
    rating: 4.5,
    review_count: 876,
    brand: 'Bose',
    isNew: true,
    discount: 11,
    delivery: 'Free Delivery',
    specifications: {
      Battery: '20 hours',
      Waterproof: 'IP67',
      Bluetooth: '5.3',
      Weight: '2.1 kg',
    },
    features: [
      'Room-filling sound',
      'IP67 waterproof',
      '20-hour battery',
      'Built-in microphone',
    ],
    createdAt: '2025-06-20',
  },
  {
    id: 'prod-28',
    name: 'MacBook Air 15" M3',
    slug: 'macbook-air-15-m3',
    description:
      'Impressively big and impossibly thin. 15.3-inch Liquid Retina display. M3 chip with 16-core Neural Engine. Up to 18 hours of battery life.',
    price: 1299,
    originalPrice: 1399,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/mba151/400/400',
      'https://picsum.photos/seed/mba152/400/400',
      'https://picsum.photos/seed/mba153/400/400',
    ],
    category_id: 'cat-4',
    category_name: 'Laptops',
    category_slug: 'laptops',
    tags: ['apple', 'laptop', 'm3', 'thin-and-light'],
    stock: 25,
    rating: 4.7,
    review_count: 1654,
    brand: 'Apple',
    isNew: false,
    discount: 7,
    delivery: 'Free Delivery',
    specifications: {
      Chip: 'Apple M3',
      Display: '15.3" Liquid Retina',
      RAM: '16GB Unified',
      Battery: '18 hours',
    },
    features: [
      '15.3-inch Liquid Retina display',
      'M3 chip with 16-core Neural Engine',
      'Up to 18 hours battery',
      '0.45 inches thin',
    ],
    createdAt: '2025-03-01',
  },
  {
    id: 'prod-29',
    name: 'Sony A7 IV Mirrorless Camera',
    slug: 'sony-a7-iv',
    description:
      'Full-frame 33MP Exmor R CMOS sensor. Real-time Eye AF for humans and animals. 4K 60p video recording. 5-axis in-body image stabilization.',
    price: 2498,
    originalPrice: 2698,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/sonycam1/400/400',
      'https://picsum.photos/seed/sonycam2/400/400',
      'https://picsum.photos/seed/sonycam3/400/400',
    ],
    category_id: 'cat-1',
    category_name: 'Electronics',
    category_slug: 'electronics',
    tags: ['sony', 'camera', 'mirrorless', 'full-frame'],
    stock: 7,
    rating: 4.7,
    review_count: 765,
    brand: 'Sony',
    isNew: false,
    discount: 7,
    delivery: 'Free Delivery',
    specifications: {
      Sensor: '33MP Full-Frame Exmor R',
      ISO: '100-51200',
      Video: '4K 60p',
      Stabilization: '5-axis IBIS',
    },
    features: [
      '33MP full-frame sensor',
      'Real-time Eye AF',
      '4K 60p video',
      '5-axis in-body stabilization',
    ],
    createdAt: '2025-02-01',
  },
  {
    id: 'prod-30',
    name: 'Nike Pro Dri-FIT Leggings',
    slug: 'nike-pro-leggings',
    description:
      'High-support leggings with Dri-FIT technology. Mesh panels for breathability. Wide waistband with hidden pocket. Perfect for training.',
    price: 85,
    originalPrice: 100,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/nikeleggings1/400/400',
      'https://picsum.photos/seed/nikeleggings2/400/400',
      'https://picsum.photos/seed/nikeleggings3/400/400',
    ],
    category_id: 'cat-2',
    category_name: 'Fashion',
    category_slug: 'fashion',
    tags: ['nike', 'leggings', 'training', 'dri-fit'],
    stock: 65,
    rating: 4.4,
    review_count: 2341,
    brand: 'Nike',
    isNew: false,
    discount: 15,
    delivery: 'Free Delivery',
    specifications: {
      Material: 'Dri-FIT',
      Fit: 'High Support',
      Waistband: 'Wide with Pocket',
      Breathability: 'Mesh Panels',
    },
    features: [
      'Dri-FIT moisture management',
      'Mesh panels for ventilation',
      'Wide waistband with pocket',
      'High-support compression',
    ],
    createdAt: '2025-03-20',
  },
  {
    id: 'prod-31',
    name: 'Dyson Airwrap Multi-Styler',
    slug: 'dyson-airwrap',
    description:
      'Style without extreme heat. Uses Coanda airflow to curl, wave, and smooth. Includes 6 attachments. Intelligent heat control.',
    price: 599,
    originalPrice: 649,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/dysonhair1/400/400',
      'https://picsum.photos/seed/dysonhair2/400/400',
      'https://picsum.photos/seed/dysonhair3/400/400',
    ],
    category_id: 'cat-8',
    category_name: 'Beauty',
    category_slug: 'beauty',
    tags: ['dyson', 'hair-styler', 'beauty', 'airwrap'],
    stock: 16,
    rating: 4.3,
    review_count: 1890,
    brand: 'Dyson',
    isNew: false,
    discount: 8,
    delivery: 'Free Delivery',
    specifications: {
      Technology: 'Coanda Airflow',
      Attachments: '6 pieces',
      'Heat Control': 'Intelligent',
      'Hair Types': 'All Types',
    },
    features: [
      'Style without extreme heat',
      'Coanda airflow technology',
      '6 included attachments',
      'Intelligent heat control',
    ],
    createdAt: '2025-04-05',
  },
  {
    id: 'prod-32',
    name: 'Samsung QN90C 75" Neo QLED TV',
    slug: 'samsung-qn90c-75',
    description:
      'Stunning Neo QLED 4K with Quantum Matrix Technology. Dolby Atmos and Object Tracking Sound+. Anti-glare screen. Slim design with One Connect box.',
    price: 2999,
    originalPrice: 3499,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/samsungtv1/400/400',
      'https://picsum.photos/seed/samsungtv2/400/400',
      'https://picsum.photos/seed/samsungtv3/400/400',
    ],
    category_id: 'cat-7',
    category_name: 'Home Appliances',
    category_slug: 'home-appliances',
    tags: ['samsung', 'tv', 'qled', '4k'],
    stock: 5,
    rating: 4.6,
    review_count: 876,
    brand: 'Samsung',
    isNew: false,
    discount: 14,
    delivery: 'Free Delivery',
    specifications: {
      Resolution: '4K UHD',
      Technology: 'Neo QLED',
      Audio: 'Dolby Atmos',
      HDMI: '4x HDMI 2.1',
    },
    features: [
      'Neo QLED with Quantum Matrix',
      'Dolby Atmos + OTS+',
      'Anti-glare screen',
      'One Connect box',
    ],
    createdAt: '2025-02-20',
  },
  {
    id: 'prod-33',
    name: 'Adidas Originals Stan Smith',
    slug: 'adidas-stan-smith',
    description:
      'Timeless tennis-inspired sneakers. Classic white leather upper with perforated 3-Stripes. Comfortable textile lining. Iconic heel tab.',
    price: 85,
    originalPrice: 100,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/stansmith1/400/400',
      'https://picsum.photos/seed/stansmith2/400/400',
      'https://picsum.photos/seed/stansmith3/400/400',
    ],
    category_id: 'cat-5',
    category_name: 'Shoes',
    category_slug: 'shoes',
    tags: ['adidas', 'sneakers', 'classic', 'tennis'],
    stock: 90,
    rating: 4.5,
    review_count: 3456,
    brand: 'Adidas',
    isNew: false,
    discount: 15,
    delivery: 'Free Delivery',
    specifications: {
      Upper: 'White Leather',
      Lining: 'Textile',
      Closure: 'Lace-up',
      Origin: 'Tennis-inspired',
    },
    features: [
      'Timeless tennis-inspired design',
      'Classic white leather upper',
      'Perforated 3-Stripes',
      'Iconic heel tab',
    ],
    createdAt: '2025-01-15',
  },
  {
    id: 'prod-34',
    name: 'Apple AirPods Pro 2nd Gen',
    slug: 'airpods-pro-2',
    description:
      'Apple H2 chip with adaptive audio. Active Noise Cancellation with Transparency mode. Personalized Spatial Audio. USB-C charging case with Find My.',
    price: 249,
    originalPrice: 279,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/airpods1/400/400',
      'https://picsum.photos/seed/airpods2/400/400',
      'https://picsum.photos/seed/airpods3/400/400',
    ],
    category_id: 'cat-1',
    category_name: 'Electronics',
    category_slug: 'electronics',
    tags: ['apple', 'earbuds', 'wireless', 'noise-cancelling'],
    stock: 55,
    rating: 4.6,
    review_count: 4567,
    brand: 'Apple',
    isNew: false,
    discount: 11,
    delivery: 'Free Delivery',
    specifications: {
      Chip: 'Apple H2',
      ANC: 'Yes',
      'Spatial Audio': 'Personalized',
      'Water Resistance': 'IPX4',
    },
    features: [
      'Adaptive audio with H2 chip',
      'Active Noise Cancellation',
      'Personalized Spatial Audio',
      'USB-C case with Find My',
    ],
    createdAt: '2025-01-01',
  },
  {
    id: 'prod-35',
    name: 'LG Gram 17 Laptop',
    slug: 'lg-gram-17',
    description:
      'Ultra-lightweight 17-inch laptop weighing only 1.35kg. Intel Core i7 with 16GB RAM. 80Wh battery for all-day productivity. MIL-STD-810H certified.',
    price: 1549,
    originalPrice: 1699,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/lggram1/400/400',
      'https://picsum.photos/seed/lggram2/400/400',
      'https://picsum.photos/seed/lggram3/400/400',
    ],
    category_id: 'cat-4',
    category_name: 'Laptops',
    category_slug: 'laptops',
    tags: ['lg', 'laptop', 'lightweight', 'premium'],
    stock: 11,
    rating: 4.3,
    review_count: 543,
    brand: 'LG',
    isNew: false,
    discount: 9,
    delivery: 'Free Delivery',
    specifications: {
      Weight: '1.35kg',
      Display: '17" WQXGA IPS',
      Battery: '80Wh',
      Durability: 'MIL-STD-810H',
    },
    features: [
      'Ultra-lightweight 1.35kg',
      '17-inch WQXGA IPS display',
      '80Wh battery',
      'MIL-STD-810H certified',
    ],
    createdAt: '2025-04-01',
  },
  {
    id: 'prod-36',
    name: 'Amazon Kindle Paperwhite (11th Gen)',
    slug: 'kindle-paperwhite-11',
    description:
      'The thinnest, lightest Kindle Paperwhite ever. 6.8" display with 300ppi. Adjustable warm light. Weeks of battery life. Waterproof (IPX8).',
    price: 139,
    originalPrice: 159,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/kindle1/400/400',
      'https://picsum.photos/seed/kindle2/400/400',
      'https://picsum.photos/seed/kindle3/400/400',
    ],
    category_id: 'cat-1',
    category_name: 'Electronics',
    category_slug: 'electronics',
    tags: ['amazon', 'kindle', 'ebook', 'reading'],
    stock: 85,
    rating: 4.6,
    review_count: 3456,
    brand: 'Amazon',
    isNew: false,
    discount: 13,
    delivery: 'Free Delivery',
    specifications: {
      Display: '6.8" 300ppi',
      Lighting: 'Adjustable Warm',
      Waterproof: 'IPX8',
      Battery: 'Weeks',
    },
    features: [
      'Thinnest and lightest Paperwhite',
      '6.8-inch 300ppi display',
      'Adjustable warm light',
      'Waterproof IPX8',
    ],
    createdAt: '2025-01-20',
  },
  {
    id: 'prod-37',
    name: 'The Alchemist by Paulo Coelho',
    slug: 'the-alchemist',
    description:
      "A magical fable about following your dream. Paulo Coelho's enchanting novel has inspired millions worldwide. A timeless story of self-discovery.",
    price: 13,
    originalPrice: 16,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/alchemist1/400/400',
      'https://picsum.photos/seed/alchemist2/400/400',
      'https://picsum.photos/seed/alchemist3/400/400',
    ],
    category_id: 'cat-9',
    category_name: 'Books',
    category_slug: 'books',
    tags: ['book', 'fiction', 'inspirational', 'classic'],
    stock: 200,
    rating: 4.5,
    review_count: 6789,
    brand: 'HarperOne',
    isNew: false,
    discount: 19,
    delivery: 'Free Delivery',
    specifications: {
      Pages: '208',
      Language: 'English',
      Publisher: 'HarperOne',
      Format: 'Paperback',
    },
    features: [
      'International bestseller',
      'Inspiring story of self-discovery',
      'Beautiful prose',
      'Life-changing wisdom',
    ],
    createdAt: '2025-01-01',
  },
  {
    id: 'prod-38',
    name: 'Atomic Habits by James Clear',
    slug: 'atomic-habits',
    description:
      'An easy and proven way to build good habits and break bad ones. Practical strategies backed by scientific research. #1 New York Times bestseller.',
    price: 16,
    originalPrice: 19,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/atomichabits1/400/400',
      'https://picsum.photos/seed/atomichabits2/400/400',
      'https://picsum.photos/seed/atomichabits3/400/400',
    ],
    category_id: 'cat-9',
    category_name: 'Books',
    category_slug: 'books',
    tags: ['book', 'self-help', 'habits', 'bestseller'],
    stock: 180,
    rating: 4.7,
    review_count: 8901,
    brand: 'Penguin',
    isNew: false,
    discount: 16,
    delivery: 'Free Delivery',
    specifications: {
      Pages: '320',
      Language: 'English',
      Publisher: 'Penguin Books',
      Format: 'Paperback',
    },
    features: [
      '#1 New York Times bestseller',
      'Proven habit-building framework',
      'Scientific research backed',
      'Practical 4-step system',
    ],
    createdAt: '2025-01-10',
  },
  {
    id: 'prod-39',
    name: 'Bowflex SelectTech 552 Dumbbells',
    slug: 'bowflex-552',
    description:
      'Adjustable dumbbells replacing 15 sets. Quick-adjust weight from 5 to 52.5 lbs. Compact storage tray. Smooth transition between weights.',
    price: 399,
    originalPrice: 499,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/bowflex1/400/400',
      'https://picsum.photos/seed/bowflex2/400/400',
      'https://picsum.photos/seed/bowflex3/400/400',
    ],
    category_id: 'cat-10',
    category_name: 'Sports',
    category_slug: 'sports',
    tags: ['bowflex', 'dumbbells', 'fitness', 'home-gym'],
    stock: 22,
    rating: 4.5,
    review_count: 2345,
    brand: 'Bowflex',
    isNew: false,
    discount: 20,
    delivery: 'Free Delivery',
    specifications: {
      'Weight Range': '5-52.5 lbs',
      Increments: '2.5 lbs',
      Dimensions: '15.8" x 8" x 9"',
      Replaces: '15 Sets',
    },
    features: [
      'Replaces 15 sets of dumbbells',
      'Quick-adjust weight dial',
      'Compact storage tray',
      'Smooth weight transition',
    ],
    createdAt: '2025-03-10',
  },
  {
    id: 'prod-40',
    name: 'Lululemon Align High-Rise Leggings',
    slug: 'lululemon-align',
    description:
      'Buttery-soft Nulu fabric for weightless comfort. High-rise waist with hidden waistband pocket. Versatile for yoga and everyday wear.',
    price: 98,
    originalPrice: 118,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/lululemon1/400/400',
      'https://picsum.photos/seed/lululemon2/400/400',
      'https://picsum.photos/seed/lululemon3/400/400',
    ],
    category_id: 'cat-2',
    category_name: 'Fashion',
    category_slug: 'fashion',
    tags: ['lululemon', 'leggings', 'yoga', 'nulu'],
    stock: 48,
    rating: 4.6,
    review_count: 3123,
    brand: 'Lululemon',
    isNew: false,
    discount: 17,
    delivery: 'Free Delivery',
    specifications: {
      Material: 'Nulu',
      Rise: 'High-Rise',
      Pockets: 'Hidden Waistband',
      Activity: 'Yoga + Everyday',
    },
    features: [
      'Buttery-soft Nulu fabric',
      'High-rise waist',
      'Hidden waistband pocket',
      'Versatile for yoga and everyday',
    ],
    createdAt: '2025-04-15',
  },
  {
    id: 'prod-41',
    name: 'OnePlus 12 5G',
    slug: 'oneplus-12',
    description:
      'Flagship killer with Snapdragon 8 Gen 3. 50MP Hasselblad triple camera. 100W SUPERVOOC charging. 2K 120Hz ProXDR display.',
    price: 799,
    originalPrice: 899,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/oneplus121/400/400',
      'https://picsum.photos/seed/oneplus122/400/400',
      'https://picsum.photos/seed/oneplus123/400/400',
    ],
    category_id: 'cat-3',
    category_name: 'Mobiles',
    category_slug: 'mobiles',
    tags: ['oneplus', 'smartphone', 'hasselblad', 'fast-charging'],
    stock: 38,
    rating: 4.4,
    review_count: 1234,
    brand: 'OnePlus',
    isNew: false,
    discount: 11,
    delivery: 'Free Delivery',
    specifications: {
      Chip: 'Snapdragon 8 Gen 3',
      Display: '6.82" 2K 120Hz',
      Camera: '50MP Hasselblad',
      Charging: '100W SUPERVOOC',
    },
    features: [
      'Snapdragon 8 Gen 3',
      'Hasselblad triple camera',
      '100W SUPERVOOC charging',
      '2K 120Hz ProXDR display',
    ],
    createdAt: '2025-02-15',
  },
  {
    id: 'prod-42',
    name: 'Bose QuietComfort 45 Headphones',
    slug: 'bose-qc-45',
    description:
      'World-class noise cancellation with Quiet/Aware modes. Triple black colorway. Up to 22 hours battery. Customizable EQ in Bose Music app.',
    price: 329,
    originalPrice: 349,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/boseqc451/400/400',
      'https://picsum.photos/seed/boseqc452/400/400',
      'https://picsum.photos/seed/boseqc453/400/400',
    ],
    category_id: 'cat-1',
    category_name: 'Electronics',
    category_slug: 'electronics',
    tags: ['bose', 'headphones', 'noise-cancelling', 'bluetooth'],
    stock: 42,
    rating: 4.5,
    review_count: 2987,
    brand: 'Bose',
    isNew: false,
    discount: 6,
    delivery: 'Free Delivery',
    specifications: {
      Battery: '22 hours',
      'Noise Cancellation': 'Quiet/Aware Modes',
      Charging: 'USB-C',
      Weight: '238g',
    },
    features: [
      'World-class noise cancellation',
      'Quiet/Aware modes',
      'Customizable EQ',
      'USB-C charging',
    ],
    createdAt: '2025-02-20',
  },
  {
    id: 'prod-43',
    name: 'Sony X90L 65" 4K Google TV',
    slug: 'sony-x90l-65',
    description:
      'Full Array LED with Cognitive Processor XR. XR Triluminos Pro for rich colors. Google TV with built-in Chromecast. Dolby Vision and Dolby Atmos.',
    price: 1198,
    originalPrice: 1398,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/sonytv1/400/400',
      'https://picsum.photos/seed/sonytv2/400/400',
      'https://picsum.photos/seed/sonytv3/400/400',
    ],
    category_id: 'cat-7',
    category_name: 'Home Appliances',
    category_slug: 'home-appliances',
    tags: ['sony', 'tv', '4k', 'google-tv'],
    stock: 9,
    rating: 4.5,
    review_count: 654,
    brand: 'Sony',
    isNew: false,
    discount: 14,
    delivery: 'Free Delivery',
    specifications: {
      Resolution: '4K HDR',
      Technology: 'Full Array LED',
      Processor: 'Cognitive XR',
      Audio: 'Dolby Atmos',
    },
    features: [
      'Full Array LED',
      'Cognitive Processor XR',
      'XR Triluminos Pro',
      'Google TV with Chromecast',
    ],
    createdAt: '2025-03-20',
  },
  {
    id: 'prod-44',
    name: "Nike Air Force 1 '07",
    slug: 'nike-air-force-1',
    description:
      'The basketball icon that transcends sport. Classic white-on-white leather upper. Nike Air cushioning. Durable rubber outsole with pivot points.',
    price: 110,
    originalPrice: 120,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/af1_1/400/400',
      'https://picsum.photos/seed/af1_2/400/400',
      'https://picsum.photos/seed/af1_3/400/400',
    ],
    category_id: 'cat-5',
    category_name: 'Shoes',
    category_slug: 'shoes',
    tags: ['nike', 'sneakers', 'classic', 'basketball'],
    stock: 110,
    rating: 4.6,
    review_count: 5678,
    brand: 'Nike',
    isNew: false,
    discount: 8,
    delivery: 'Free Delivery',
    specifications: {
      Upper: 'Leather',
      Cushioning: 'Nike Air',
      Outsole: 'Rubber',
      Closure: 'Lace-up',
    },
    features: [
      'Basketball icon',
      'Classic white leather',
      'Nike Air cushioning',
      'Durable rubber outsole',
    ],
    createdAt: '2025-01-05',
  },
  {
    id: 'prod-45',
    name: 'JBL Tune 770NC Headphones',
    slug: 'jbl-tune-770nc',
    description:
      'Wireless over-ear headphones with True Adaptive Noise Cancelling. Pure Bass Sound with JBL Signature Sound. Up to 70 hours of battery.',
    price: 129,
    originalPrice: 199,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/jbl7701/400/400',
      'https://picsum.photos/seed/jbl7702/400/400',
      'https://picsum.photos/seed/jbl7703/400/400',
    ],
    category_id: 'cat-1',
    category_name: 'Electronics',
    category_slug: 'electronics',
    tags: ['jbl', 'headphones', 'noise-cancelling', 'wireless'],
    stock: 75,
    rating: 4.3,
    review_count: 1876,
    brand: 'JBL',
    isNew: false,
    discount: 35,
    delivery: 'Free Delivery',
    specifications: {
      Battery: '70 hours',
      'Noise Cancellation': 'Adaptive',
      Driver: '40mm',
      Weight: '220g',
    },
    features: [
      'True Adaptive Noise Cancelling',
      'Pure Bass Sound',
      '70-hour battery',
      'Comfortable over-ear design',
    ],
    createdAt: '2025-05-10',
  },
  {
    id: 'prod-46',
    name: 'Dyson V8 Origin Cordless Vacuum',
    slug: 'dyson-v8-origin',
    description:
      'Up to 40 minutes of fade-free suction. Whole-machine filtration traps allergens. Direct-drive cleaner head. Versatile handheld conversion.',
    price: 399,
    originalPrice: 449,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/dysonv81/400/400',
      'https://picsum.photos/seed/dysonv82/400/400',
      'https://picsum.photos/seed/dysonv83/400/400',
    ],
    category_id: 'cat-7',
    category_name: 'Home Appliances',
    category_slug: 'home-appliances',
    tags: ['dyson', 'vacuum', 'cordless', 'filtration'],
    stock: 32,
    rating: 4.4,
    review_count: 4321,
    brand: 'Dyson',
    isNew: false,
    discount: 11,
    delivery: 'Free Delivery',
    specifications: {
      'Run Time': '40 min',
      Filtration: 'Whole-machine',
      Capacity: '0.54L',
      Weight: '5.5 lbs',
    },
    features: [
      '40 minutes fade-free suction',
      'Whole-machine HEPA filtration',
      'Direct-drive cleaner head',
      'Converts to handheld',
    ],
    createdAt: '2025-02-01',
  },
  {
    id: 'prod-47',
    name: 'Ray-Ban Clubmaster Classic',
    slug: 'rayban-clubmaster',
    description:
      'Iconic browline frame design. Premium acetate construction. Green G-15 lenses with UV protection. Spring hinge temples for comfortable fit.',
    price: 153,
    originalPrice: 193,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/clubmaster1/400/400',
      'https://picsum.photos/seed/clubmaster2/400/400',
      'https://picsum.photos/seed/clubmaster3/400/400',
    ],
    category_id: 'cat-12',
    category_name: 'Accessories',
    category_slug: 'accessories',
    tags: ['rayban', 'sunglasses', 'clubmaster', 'classic'],
    stock: 40,
    rating: 4.4,
    review_count: 1654,
    brand: 'Ray-Ban',
    isNew: false,
    discount: 21,
    delivery: 'Free Delivery',
    specifications: {
      Frame: 'Acetate',
      Lens: 'Green G-15',
      Protection: '100% UV',
      Temple: 'Spring Hinge',
    },
    features: [
      'Iconic browline design',
      'Premium acetate frame',
      'Green G-15 lenses',
      'Spring hinge temples',
    ],
    createdAt: '2025-04-25',
  },
  {
    id: 'prod-48',
    name: 'KitchenAid 2-Slice Toaster',
    slug: 'kitchenaid-toaster',
    description:
      'Professional-style toaster with All Metal construction. 7 shade settings with LED indicators. Self-centering racks for even toasting. Extra-wide slots.',
    price: 149,
    originalPrice: 179,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/ktoaster1/400/400',
      'https://picsum.photos/seed/ktoaster2/400/400',
      'https://picsum.photos/seed/ktoaster3/400/400',
    ],
    category_id: 'cat-7',
    category_name: 'Home Appliances',
    category_slug: 'home-appliances',
    tags: ['kitchenaid', 'toaster', 'kitchen', 'appliance'],
    stock: 28,
    rating: 4.3,
    review_count: 876,
    brand: 'KitchenAid',
    isNew: false,
    discount: 17,
    delivery: 'Free Delivery',
    specifications: {
      Slots: '2 Extra-wide',
      Settings: '7 Shade',
      Construction: 'All Metal',
      Features: 'LED Indicators',
    },
    features: [
      'All Metal construction',
      '7 shade settings with LED',
      'Self-centering racks',
      'Extra-wide slots',
    ],
    createdAt: '2025-05-01',
  },
  {
    id: 'prod-49',
    name: 'Fitbit Charge 6',
    slug: 'fitbit-charge-6',
    description:
      'Advanced fitness tracker with built-in GPS. Google integration with Maps and Wallet. Heart rate tracking with ECG. Stress management with EDA sensor.',
    price: 159,
    originalPrice: 179,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/fitbit1/400/400',
      'https://picsum.photos/seed/fitbit2/400/400',
      'https://picsum.photos/seed/fitbit3/400/400',
    ],
    category_id: 'cat-10',
    category_name: 'Sports',
    category_slug: 'sports',
    tags: ['fitbit', 'fitness', 'tracker', 'health'],
    stock: 55,
    rating: 4.2,
    review_count: 2341,
    brand: 'Fitbit',
    isNew: false,
    discount: 11,
    delivery: 'Free Delivery',
    specifications: {
      Sensors: 'Heart Rate, ECG, EDA',
      GPS: 'Built-in',
      Battery: '7 days',
      'Water Resistance': '50m',
    },
    features: [
      'Built-in GPS',
      'Google Maps + Wallet',
      'ECG heart rate tracking',
      'Stress management with EDA',
    ],
    createdAt: '2025-02-25',
  },
  {
    id: 'prod-50',
    name: "Levi's Trucker Denim Jacket",
    slug: 'levis-trucker-jacket',
    description:
      "The iconic Levi's Trucker Jacket since 1962. Classic button-front design with point collar. Adjustable waistband. Signature tab detailing.",
    price: 98,
    originalPrice: 128,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/levisjacket1/400/400',
      'https://picsum.photos/seed/levisjacket2/400/400',
      'https://picsum.photos/seed/levisjacket3/400/400',
    ],
    category_id: 'cat-2',
    category_name: 'Fashion',
    category_slug: 'fashion',
    tags: ['levis', 'jacket', 'denim', 'classic'],
    stock: 35,
    rating: 4.5,
    review_count: 1890,
    brand: "Levi's",
    isNew: false,
    discount: 23,
    delivery: 'Free Delivery',
    specifications: {
      Material: 'Denim',
      Closure: 'Button-front',
      Collar: 'Point',
      Fit: 'Classic',
    },
    features: [
      'Iconic Trucker Jacket since 1962',
      'Button-front design',
      'Adjustable waistband',
      'Signature tab detailing',
    ],
    createdAt: '2025-03-30',
  },
  {
    id: 'prod-51',
    name: 'Sony WF-1000XM5 Earbuds',
    slug: 'sony-wf-1000xm5',
    description:
      'The best truly wireless noise cancelling earbuds. New Integrated Processor V2. Hi-Res Audio with DSEE Extreme. IPX4 water resistant.',
    price: 278,
    originalPrice: 328,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/sonyxm51/400/400',
      'https://picsum.photos/seed/sonyxm52/400/400',
      'https://picsum.photos/seed/sonyxm53/400/400',
    ],
    category_id: 'cat-1',
    category_name: 'Electronics',
    category_slug: 'electronics',
    tags: ['sony', 'earbuds', 'noise-cancelling', 'hi-res'],
    stock: 48,
    rating: 4.6,
    review_count: 1876,
    brand: 'Sony',
    isNew: true,
    discount: 15,
    delivery: 'Free Delivery',
    specifications: {
      Battery: '8h (24h with case)',
      Processor: 'Integrated V2',
      Audio: 'Hi-Res + DSEE Extreme',
      Waterproof: 'IPX4',
    },
    features: [
      'Best-in-class noise cancellation',
      'Integrated Processor V2',
      'Hi-Res Audio with DSEE Extreme',
      'IPX4 water resistant',
    ],
    createdAt: '2025-06-10',
  },
  {
    id: 'prod-52',
    name: 'Samsung Galaxy Book4 Ultra',
    slug: 'samsung-book4-ultra',
    description:
      '16-inch 3K AMOLED display with 120Hz. Intel Core Ultra 9 with NVIDIA RTX 4070. Galaxy AI features for seamless productivity. AKG quad speakers.',
    price: 2399,
    originalPrice: 2699,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/galaxybook1/400/400',
      'https://picsum.photos/seed/galaxybook2/400/400',
      'https://picsum.photos/seed/galaxybook3/400/400',
    ],
    category_id: 'cat-4',
    category_name: 'Laptops',
    category_slug: 'laptops',
    tags: ['samsung', 'laptop', 'amoled', 'ai'],
    stock: 8,
    rating: 4.4,
    review_count: 432,
    brand: 'Samsung',
    isNew: true,
    discount: 11,
    delivery: 'Free Delivery',
    specifications: {
      Processor: 'Intel Core Ultra 9',
      GPU: 'NVIDIA RTX 4070',
      Display: '16" 3K AMOLED 120Hz',
      RAM: '32GB',
    },
    features: [
      '16" 3K AMOLED 120Hz display',
      'Intel Core Ultra 9',
      'NVIDIA RTX 4070',
      'Galaxy AI features',
    ],
    createdAt: '2025-06-05',
  },
  {
    id: 'prod-53',
    name: 'Nintendo Switch OLED',
    slug: 'nintendo-switch-oled',
    description:
      'Meet the newest member of the Nintendo Switch family. 7-inch OLED screen with vivid colors. Wide adjustable stand. 64GB internal storage. Enhanced audio.',
    price: 349,
    originalPrice: 349,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/nswitch1/400/400',
      'https://picsum.photos/seed/nswitch2/400/400',
      'https://picsum.photos/seed/nswitch3/400/400',
    ],
    category_id: 'cat-15',
    category_name: 'Toys',
    category_slug: 'toys',
    tags: ['nintendo', 'switch', 'gaming', 'console'],
    stock: 20,
    rating: 4.7,
    review_count: 3456,
    brand: 'Nintendo',
    isNew: false,
    discount: 0,
    delivery: 'Free Delivery',
    specifications: {
      Display: '7" OLED',
      Storage: '64GB',
      Battery: '4.5-9 hours',
      Weight: '420g',
    },
    features: [
      '7-inch OLED screen',
      'Wide adjustable stand',
      '64GB internal storage',
      'Enhanced audio',
    ],
    createdAt: '2025-01-01',
  },
  {
    id: 'prod-54',
    name: 'LEGO Star Wars Millennium Falcon',
    slug: 'lego-millennium-falcon',
    description:
      'Build the most detailed Millennium Falcon ever! 7,500+ pieces. Features detailed interior, lowering ramp, and rotating turrets. For ages 16+.',
    price: 849,
    originalPrice: 849,
    currency: 'USD',
    images: [
      'https://picsum.photos/seed/legomf1/400/400',
      'https://picsum.photos/seed/legomf2/400/400',
      'https://picsum.photos/seed/legomf3/400/400',
    ],
    category_id: 'cat-15',
    category_name: 'Toys',
    category_slug: 'toys',
    tags: ['lego', 'star-wars', 'building-set', 'collector'],
    stock: 5,
    rating: 4.9,
    review_count: 1234,
    brand: 'LEGO',
    isNew: false,
    discount: 0,
    delivery: 'Free Delivery',
    specifications: {
      Pieces: '7,541',
      Age: '16+',
      Minifigures: '7',
      Dimensions: '33" x 22" x 8"',
    },
    features: [
      'Ultra-detailed 7,541-piece build',
      'Detailed interior and exterior',
      '7 minifigures included',
      'Iconic Star Wars collectible',
    ],
    createdAt: '2025-01-15',
  },
]

export const products = baseProducts
export const bestSellers = baseProducts
  .filter((p) => p.rating >= 4.6)
  .slice(0, 10)
export const newArrivals = [...baseProducts]
  .sort(
    (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
  )
  .slice(0, 10)
export const flashSales = baseProducts
  .filter((p) => p.discount >= 20)
  .slice(0, 6)
export const brands = [...new Set(baseProducts.map((p) => p.brand))].sort()

export const deals: DealItem[] = [
  { product: baseProducts[0], endsIn: '2h 30m', label: 'Deal of the Day' },
  { product: baseProducts[17], endsIn: '5h 15m', label: 'Limited Offer' },
  { product: baseProducts[3], endsIn: '1h 45m', label: 'Flash Sale' },
  { product: baseProducts[48], endsIn: '3h 20m', label: 'Special Price' },
  { product: baseProducts[44], endsIn: '6h 00m', label: 'Todays Deal' },
]

export function getProductById(id: string): ExtendedProduct | undefined {
  return baseProducts.find((p) => p.id === id)
}

export function getProductsByCategory(slug: string): ExtendedProduct[] {
  return baseProducts.filter((p) => p.category_slug === slug)
}

export function getRelatedProducts(
  productId: string,
  limit = 6
): ExtendedProduct[] {
  const product = baseProducts.find((p) => p.id === productId)
  if (!product) return []
  return baseProducts
    .filter(
      (p) => p.id !== productId && p.category_slug === product.category_slug
    )
    .slice(0, limit)
}

export function getProductBySlug(slug: string): ExtendedProduct | undefined {
  return baseProducts.find((p) => p.slug === slug)
}

export function searchProducts(query: string): ExtendedProduct[] {
  const q = query.toLowerCase()
  return baseProducts.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.brand.toLowerCase().includes(q) ||
      p.category_name.toLowerCase().includes(q) ||
      p.tags.some((t) => t.toLowerCase().includes(q))
  )
}

export function getProductsByCategorySlug(slug: string): ExtendedProduct[] {
  return baseProducts.filter((p) => p.category_slug === slug)
}
